task_1
eugene-okulik/marina pull request #26
Opened 2024-04-09 20:50 UTC by Marina1824

Не без помощи гпт, но старалась разобраться во всем. Очень много кода, в основном сложность возникла с взятием нескольких id и потом с выводом последнего запроса через join

2024-04-09 20:59 UTC, Marina1824 commented
@eugene-okulik не получается залить на проверку. Можете посмотреть?

2024-04-10 11:57 UTC, eugene-okulik requested changes
Поправь эту `f` и закроем.  
В остальном, все отлично. Единственное, у тебя местами используется подстановка с помощью %s, а местами питоновская подстановка. Лучше везде пользоваться подстановкой через %s

2024-04-10 11:57 UTC, eugene-okulik commented on homework/morera_marina/homework_15/task_1.py
> +query = f'''SELECT DISTINCT s.name, s.second_name, g.title, b.title, s2.title, l.title, m.value
Вот здесь в запросе перед кавычками нужно убрать `f` и не будет ошибок.

2024-04-12 07:35 UTC, eugene-okulik approved these changes

2024-04-12 07:35 UTC, merged