Homework 27
eugene-okulik/marina pull request #44
Opened 2024-08-26 19:43 UTC by Marina1824

2024-08-26 19:57 UTC, Marina1824 commented
@eugene-okulik  Можешь посмотреть что не так, пожалуйста?

2024-08-27 08:45 UTC, eugene-okulik commented
> @eugene-okulik Можешь посмотреть что не так, пожалуйста?

Тебе просто нужно избавиться от папки myenv в репозитории. Обычно виртуальное окружение создают в папке venv и репозитории по дефолту защищают от того, чтобы туда эта папка попала, но ты придумала свое название папки, значит тебе или нужно было добавить это название в .gitignore или просто следить за тем, чтобы эта папка не улетела в гитхаб (не выполнять для нее git add). А сейчас тебе нужно удалить эту папку, сделать коммит, добавить название этой папки в .gitignore и снова создать виртуальное окружение, сделать коммит и пуш. И сделать всё именно в этой последовательности.

2024-08-27 08:47 UTC, eugene-okulik requested changes
нужно избавиться от папки myenv

2024-08-28 06:38 UTC, eugene-okulik approved these changes

2024-08-28 06:38 UTC, merged