Test UI unique name
eugene-okulik/marina pull request #46
Opened 2024-09-16 13:37 UTC by Marina1824

добила, но есть такая проблема кажется у сайте. При запуске тестов в валидационном сообщении может приходить "Invalid Form Key. Please refresh the page." вместо условно Успешно добавлено или Нужна регистрация. Только при перезапуске помогает. Не знаю с чем связано, но нервы потрепало

2024-09-17 08:44 UTC, eugene-okulik requested changes

2024-09-17 08:44 UTC, eugene-okulik commented on homework/morera_marina/test_UI_unique_name/test/test_links_and_compare_with_delete.py
> +    sales.add_to_compare_and_delete()
Эти тесты выглядят так, как будто в них есть шаги, но нет проверок. Я вижу, что проверки добавлены внутри методов. Нужно или методы назвать так, чтобы было понятно, что они не только делают действие, но и проверяют результат. Но еще лучше - разделить это на два метода. Один делает, второй проверяет.

2024-09-17 08:44 UTC, eugene-okulik commented on homework/morera_marina/test_UI_unique_name/pages/sales.py
> +        shop_women = self.page.locator('text="Shop Women’s Deals"')
Для всех локаторов лучше сделать отдельный файл и хранить их там. Ведь часто бывают ситуации, когда один и тот же локатор нужен разным методам и тогда приходится его дублировать. Но и для поддержки тестов это тоже удобно - когда все локаторы находятся в одном месте.

2024-09-17 08:44 UTC, eugene-okulik commented on homework/morera_marina/test_UI_unique_name/test/test_filter_compare_whishlist.py
> +    shop_luma.add_item_to_compare()
И эти тесты выглядят так, будто в них нет проверок

2024-09-17 08:44 UTC, eugene-okulik commented on homework/morera_marina/test_UI_unique_name/test/conftest.py
Этот файл должен находиться в корне проекта, а не в папке с тестами.

2024-09-17 08:44 UTC, eugene-okulik commented on homework/morera_marina/test_UI_unique_name/pages/customer_login.py
> +        self.page.goto('https://magento.softwaretestingboard.com/customer/account/create/')
В каждом классе у тебя есть одинаковый метод open_page. Вместо дублирования кода, можно создать класс base_page, где и собрать всё, что используется во всех классах.

2024-09-17 08:44 UTC, eugene-okulik commented on homework/morera_marina/test_UI_unique_name/pages/customer_login.py
> +        self.page = page
И метод `__init__` - абсолютно одинаковый во всех классах. Его тоже можно унести в base_page, как я показывал в видео.

2024-09-17 08:44 UTC, eugene-okulik commented on homework/morera_marina/test_UI_unique_name/.gitignore
Этот файл уже есть в нашем проекте. Здесь его создавать не нужно.

2024-09-18 07:56 UTC, eugene-okulik requested changes
Олично. Base page на месте. Жду остального  
И там линт на что-то ругается - нужно его тоже починить

2024-09-19 11:31 UTC, eugene-okulik requested changes
Отлично. Из одного класса локаторы убрала, осталось из остальных убрать.  
Ну и доделать всё, на что я коментарии оставлял  
И линт всё еще ругается на что-то

2024-09-19 13:12 UTC, Marina1824 commented
Сделала. Но конфтест не перенесла, ни в какую не хотел запускать тесты

2024-09-20 07:46 UTC, eugene-okulik requested changes

2024-09-20 07:46 UTC, eugene-okulik commented on homework/morera_marina/test_UI_unique_name/test/test_links_and_compare_with_delete.py
> +    sales.open_women_items('https://magento.softwaretestingboard.com/promotions/women-sale.html')
Этот тест все еще выглядит так, что он заканчивается открытием страницы и ничего не проверяет

2024-09-20 07:46 UTC, eugene-okulik commented on homework/morera_marina/test_UI_unique_name/test/test_links_and_compare_with_delete.py
> +    sales.delete_from_compare(added_item)
Этот тест выглядит так, что он удаляет что-то из сравнения и ничего не проверяет

2024-09-20 07:46 UTC, eugene-okulik commented on homework/morera_marina/test_UI_unique_name/test/conftest.py
Этот файл всё еще хочет чтобы его перенесли в корень проекта

2024-09-20 07:46 UTC, eugene-okulik commented on homework/morera_marina/test_UI_unique_name/.gitignore
Этот файл всё еще не понимает зачем он нужен, ведь в корне репозитория уже есть такой и он содержит всё, что есть в здесь.

2024-09-21 07:40 UTC, eugene-okulik approved these changes

2024-09-21 07:40 UTC, merged