Homework_4
eugene-okulik/marina pull request #5
Opened 2024-01-19 12:41 UTC by Marina1824

Действия с элементами словаря my_dict

2024-01-20 19:09 UTC, eugene-okulik requested changes
Всё хорошо, но проверку на внимательность не прошла

2024-01-20 19:09 UTC, eugene-okulik commented on homework/morera_marina/homework_4/task_1.py
> +new_dict['i am a tuple'] = 'nope'
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

А ты выполнила так, будто там:

> добавьте элемент с ключом 'i am a tuple' и любым значением

Текст ключа намекает на то, что должно быть ключом.

2024-01-21 17:30 UTC, Marina1824 commented
Поправила. Но не очень поняла, так ли нужно было сделать?

2024-01-22 15:06 UTC, eugene-okulik approved these changes

2024-01-22 15:06 UTC, merged