Homework_5
eugene-okulik/marina pull request #7
Opened 2024-01-23 14:29 UTC by Marina1824

Выполнение трёх задач из урока 5

2024-01-24 15:26 UTC, eugene-okulik requested changes

2024-01-24 15:26 UTC, eugene-okulik commented on homework/morera_marina/homework_5/task_2.py
> +result_a = a.index('42')
Смотри, если мы знаем какое число там будет еще при создании программы, то можно просто написать `print(42 + 10)`.  
Программа должна найти в строке число, которое она потом использует в вычислениях. Для этого нужно найти в этих строках что-то одинаковое. Количество символов до числа разное, количество символов в числе тоже разное. Но кое-что в структуре всех строк есть одинаковое.  
Если будут вопросы, пиши в телеграм.

2024-01-24 15:26 UTC, eugene-okulik commented on homework/morera_marina/homework_5/task_2.py
> +new_a = int((a[result_a:]))
Чота скобок вроде бы много, или меня глючит?

2024-01-24 16:20 UTC, Marina1824 commented on homework/morera_marina/homework_5/task_2.py
> +new_a = int((a[result_a:]))
Ага, это я сперва сразу в принт засунула, а потом решила вынести в переменную и не удалила)

2024-01-24 16:25 UTC, Marina1824 commented on homework/morera_marina/homework_5/task_2.py
> +result_a = a.index('42')
Я поправила, наверно, выглядит как костыль :D

2024-01-25 11:40 UTC, eugene-okulik approved these changes
Отличный костыль! Да, это костыльное решение. Правильнее здесь сделать через `split`, но задание именно через `index`

2024-01-25 11:40 UTC, merged